---
  - hosts: servers
    gather_facts: no
    roles:
      - docker_install

  - hosts: nginx
    gather_facts: no
    roles:
      - nginx


  - hosts: web_app
    gather_facts: no
    roles:
      - web_app
