---
# tasks file for nginx

#  - name: create a directory if it does not exist
#    become: yes
#    file:
#      path: /var/nginx_con/
#      state: directory
#      mode: '0775'
#      owner: ansible
#      group: docker

  - name: Install Nginx
    docker_container:
      name: nginx
      image: nginx
      detach: True
      state: started 
      ports:
        - 80:80
      expose:
        - '80'
      volumes:
        - /var/nginx_con/nginx.conf:/etc/nginx/nginx.conf:ro
    vars:
      ansible_python_interpreter: /usr/bin/python3

  - name: change nginx config
    become: yes
    template:
      src: nginx.j2.conf
      dest: /var/nginx_con/nginx.conf
      owner: ansible
      group: docker
      mode: 0664
    notify:
      - restart nginx
                
#ansible-galaxy collection install ansible.posix
  - name: open port 80
    become: yes
    firewalld:
      zone: public
      port: 80/tcp
      permanent: true
      state: enabled
    notify:
      - Restart firewalld

  - name: disable selinux
    become: yes
    selinux:
      state: disabled

